# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-11-12 18:05
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cierres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cita', models.DateField()),
                ('observacion', models.CharField(blank=True, max_length=10000, null=True)),
                ('fecha_solicitud', models.DateTimeField(blank=True, null=True)),
                ('prima_target', models.CharField(blank=True, max_length=1000, null=True)),
                ('prima_anual', models.CharField(blank=True, max_length=1000, null=True)),
                ('fecha_poliza', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField()),
                ('inforce', models.BooleanField()),
                ('agente_equipo', models.IntegerField(blank=True, null=True)),
                ('numero_poliza', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'verbose_name': 'Cierre',
                'db_table': 'citas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cita', models.DateField()),
                ('observacion', models.CharField(blank=True, max_length=10000, null=True)),
                ('fecha_solicitud', models.DateTimeField(blank=True, null=True)),
                ('prima_target', models.IntegerField(blank=True, max_length=1000, null=True)),
                ('prima_anual', models.IntegerField(blank=True, max_length=1000, null=True)),
                ('fecha_poliza', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('inforce', models.BooleanField()),
                ('agente_equipo', models.IntegerField(blank=True, null=True)),
                ('numero_poliza', models.CharField(blank=True, max_length=1000, null=True)),
                ('upload_csv', models.BooleanField(default=0)),
                ('asesor_anterior', models.CharField(blank=True, max_length=10000, null=True)),
                ('valida_pos', models.BooleanField(default=0)),
            ],
            options={
                'verbose_name': 'POS',
                'db_table': 'citas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Agente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_personal', models.IntegerField(blank=True, null=True)),
                ('meta_requerida', models.IntegerField(blank=True, null=True)),
                ('meta_equipo', models.IntegerField(blank=True, null=True)),
                ('fecha_ingreso', models.DateTimeField(blank=True, null=True)),
                ('correo_capital', models.CharField(blank=True, max_length=1000, null=True)),
                ('photo', models.FileField(blank=True, null=True, upload_to='static')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('nombre', models.CharField(blank=True, max_length=1000, null=True)),
                ('apellidos', models.CharField(blank=True, max_length=1000, null=True)),
                ('dni', models.CharField(blank=True, max_length=1000, null=True)),
                ('direccion', models.CharField(blank=True, max_length=1000, null=True)),
                ('telefono', models.CharField(blank=True, max_length=1000, null=True)),
                ('telefono_1', models.CharField(blank=True, max_length=1000, null=True)),
                ('relacion_contacto', models.CharField(blank=True, max_length=1000, null=True)),
                ('telefono_contacto_emergencia', models.CharField(blank=True, max_length=1000, null=True)),
                ('contacto_emergencia', models.CharField(blank=True, max_length=1000, null=True)),
                ('correo_personal', models.CharField(blank=True, max_length=1000, null=True)),
                ('movil_contacto', models.CharField(blank=True, max_length=1000, null=True)),
                ('version', models.CharField(blank=True, max_length=1000, null=True)),
                ('codigo', models.CharField(blank=True, max_length=1000, null=True)),
                ('tipo_movil', models.CharField(blank=True, max_length=1000, null=True)),
                ('asesor_anterior', models.CharField(blank=True, max_length=1000, null=True)),
                ('modelo', models.CharField(blank=True, max_length=1000, null=True)),
                ('version_movil', models.CharField(blank=True, max_length=1000, null=True)),
                ('hispana_seguros', models.BooleanField(default=False)),
                ('fpi', models.BooleanField(default=False)),
                ('gi', models.BooleanField(default=False)),
                ('bmiec_salud', models.BooleanField(default=False)),
                ('cfp', models.BooleanField(default=False)),
                ('mapfre', models.BooleanField(default=False)),
                ('equinoccial', models.BooleanField(default=False)),
                ('qbe', models.BooleanField(default=False)),
                ('chubb', models.BooleanField(default=False)),
                ('liberty', models.BooleanField(default=False)),
                ('it', models.BooleanField(default=False)),
                ('bupa', models.BooleanField(default=False)),
                ('bmi_health', models.BooleanField(default=False)),
                ('pc', models.BooleanField(default=False)),
                ('paiic', models.BooleanField(default=False)),
                ('nwl', models.BooleanField(default=False)),
                ('bmi_life', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('nombre',),
                'verbose_name': 'Agente',
                'db_table': 'agente',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Agentecliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agente', models.ForeignKey(db_column='agente', default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Agente')),
            ],
            options={
                'db_table': 'agentecliente',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Agentejerarquia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agente', models.ForeignKey(db_column='agente', default=142, on_delete=django.db.models.deletion.DO_NOTHING, related_name='agente_asigna', to='app.Agente', verbose_name='Agente a asignar')),
                ('bussiness_partner', models.ForeignKey(db_column='bussiness_partner', default=142, on_delete=django.db.models.deletion.DO_NOTHING, related_name='bussiness_partner', to='app.Agente', verbose_name='Business Partner')),
                ('country_manager', models.ForeignKey(db_column='country_manager', default=142, on_delete=django.db.models.deletion.DO_NOTHING, related_name='country_manager', to='app.Agente', verbose_name='Country Manager')),
                ('private_client', models.ForeignKey(db_column='private_client', default=142, on_delete=django.db.models.deletion.DO_NOTHING, related_name='private_client', to='app.Agente', verbose_name='Private Client')),
                ('private_client_senior', models.ForeignKey(db_column='private_client_senior', default=142, on_delete=django.db.models.deletion.DO_NOTHING, related_name='private_client_senior', to='app.Agente', verbose_name='Private Client Senior')),
                ('relation_management', models.ForeignKey(db_column='relation_management', default=142, on_delete=django.db.models.deletion.DO_NOTHING, related_name='relation_management', to='app.Agente', verbose_name='Relation Management')),
                ('relation_management_senior', models.ForeignKey(db_column='relation_management_senior', default=142, on_delete=django.db.models.deletion.DO_NOTHING, related_name='relation_management_senior', to='app.Agente', verbose_name='Relation Management Senior')),
                ('relation_ship_director', models.ForeignKey(db_column='relation_ship_director', default=142, on_delete=django.db.models.deletion.DO_NOTHING, related_name='relation_ship_director', to='app.Agente', verbose_name='Relation Ship Director')),
            ],
            options={
                'verbose_name': 'Agente / Jerarquia',
                'db_table': 'agentejerarquia',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruta', models.FileField(max_length=100000, upload_to='static')),
                ('nombre', models.CharField(blank=True, max_length=10000, null=True)),
                ('tipo_archivo', models.CharField(choices=[('Formulario', 'Formulario'), ('Comercial', 'Comercial')], max_length=1000)),
                ('inhouse', models.BooleanField(default=False)),
                ('broker', models.BooleanField(default=False)),
                ('peru', models.BooleanField(default=False)),
                ('ecuador', models.BooleanField(default=False)),
                ('colombia', models.BooleanField(default=False)),
                ('estados_unidos', models.BooleanField(default=False, verbose_name='Estados Unidos')),
                ('bolivia', models.BooleanField(default=False)),
                ('ramos_generales', models.BooleanField(default=False)),
                ('investments', models.BooleanField(default=False)),
                ('salud', models.BooleanField(default=False)),
                ('vida', models.BooleanField(default=False)),
                ('hispana_seguros', models.BooleanField(default=False)),
                ('fpi', models.BooleanField(default=False)),
                ('gi', models.BooleanField(default=False)),
                ('bmiec_salud', models.BooleanField(default=False)),
                ('cfp', models.BooleanField(default=False)),
                ('mapfre', models.BooleanField(default=False)),
                ('equinoccial', models.BooleanField(default=False)),
                ('qbe', models.BooleanField(default=False)),
                ('chubb', models.BooleanField(default=False)),
                ('liberty', models.BooleanField(default=False)),
                ('it', models.BooleanField(default=False)),
                ('bupa', models.BooleanField(default=False)),
                ('bmi_health', models.BooleanField(default=False)),
                ('pc', models.BooleanField(default=False)),
                ('paiic', models.BooleanField(default=False)),
                ('nwl', models.BooleanField(default=False)),
                ('bmi_life', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Biblioteca',
                'db_table': 'archivos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Citas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cita', models.DateTimeField()),
                ('observacion', models.CharField(blank=True, max_length=10000, null=True)),
                ('fecha_solicitud', models.DateTimeField(blank=True, null=True)),
                ('prima_target', models.CharField(blank=True, max_length=1000, null=True)),
                ('prima_anual', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_poliza', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('inforce', models.BooleanField(default=False)),
                ('agente_equipo', models.IntegerField(blank=True, null=True)),
                ('numero_poliza', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Numero Poliza')),
                ('cliente_cita_equipo', models.CharField(blank=True, max_length=1000, null=True)),
                ('propuesta_cita_equipo', models.CharField(blank=True, max_length=1000, null=True)),
                ('cliente_antiguo', models.CharField(blank=True, default='No', max_length=1000, null=True)),
                ('upload_csv', models.BooleanField(default=0)),
                ('asesor_anterior', models.CharField(blank=True, max_length=10000, null=True)),
                ('valida_pos', models.BooleanField(default=0)),
                ('upload_csv_julio_enero_2019', models.BooleanField(default=0)),
                ('upload_ene_jul_2019_ecu', models.BooleanField(default=0)),
                ('agente', models.ForeignKey(db_column='agente', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Agente')),
                ('agente_cita_equipo', models.ForeignKey(blank=True, db_column='agente_cita_equipo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='agente_cita_equipo', to='app.Agente')),
            ],
            options={
                'ordering': ('agente',),
                'verbose_name': 'Cita',
                'db_table': 'citas',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Cliente')),
                ('apellido', models.CharField(blank=True, max_length=1000, null=True)),
                ('email', models.CharField(blank=True, max_length=1000, null=True)),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('telefono', models.CharField(blank=True, max_length=1000, null=True)),
                ('direccion', models.CharField(blank=True, max_length=1000, null=True)),
                ('numero_hijos', models.IntegerField(blank=True, null=True)),
                ('dni', models.CharField(blank=True, max_length=1000, null=True)),
                ('conyuge', models.CharField(blank=True, max_length=1000, null=True)),
                ('edad_conyuge', models.IntegerField(blank=True, null=True)),
                ('fecha_nacimiento_conyuge', models.DateField(blank=True, null=True)),
                ('upload_csv', models.BooleanField(default=0)),
                ('upload_csv_julio_enero_2019', models.BooleanField(default=0)),
                ('upload_ene_jul_2019_ecu', models.BooleanField(default=0)),
                ('agente', models.ForeignKey(db_column='agente', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Agente')),
            ],
            options={
                'ordering': ('nombre',),
                'verbose_name': 'Cliente',
                'db_table': 'cliente',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Compania',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Compania')),
            ],
            options={
                'verbose_name': 'Compania',
                'db_table': 'compania',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Equipo',
                'db_table': 'equipo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'estado',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EstadoCivil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10000)),
            ],
            options={
                'verbose_name': 'Estado Civil',
                'db_table': 'estado_civil',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Estructura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name': 'Estructura',
                'db_table': 'estructura',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'grupo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Iconos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=10000, null=True)),
                ('icono', models.CharField(blank=True, max_length=10000, null=True)),
            ],
            options={
                'verbose_name': 'Icono',
                'db_table': 'iconos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Jerarquia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'jerarquia',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=1000, null=True)),
                ('subtitulo', models.CharField(blank=True, max_length=1000, null=True)),
                ('contenido', models.CharField(blank=True, max_length=1000, null=True)),
                ('fecha_programada', models.DateTimeField(blank=True, null=True)),
                ('sms', models.BooleanField(default=0)),
                ('notificacion', models.BooleanField(default=0)),
                ('email', models.BooleanField(default=0)),
                ('activado', models.BooleanField(default=0)),
            ],
            options={
                'db_table': 'mensaje',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Mes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=1000, verbose_name='Mes')),
            ],
            options={
                'verbose_name': 'Mes',
                'db_table': 'mes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Modalidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name': 'Forma Pago',
                'db_table': 'modalidad',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=1000)),
                ('descripcion', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'nivel',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField(blank=True, max_length=10000, null=True)),
                ('fecha', models.DateTimeField(default=datetime.datetime(2018, 11, 12, 18, 5, 46, 106333))),
                ('agente', models.ForeignKey(blank=True, db_column='agente', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Agente')),
                ('nivel', models.ForeignKey(blank=True, db_column='nivel', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Nivel')),
            ],
            options={
                'db_table': 'notificacion',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'verbose_name': 'Paise',
                'db_table': 'pais',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ParientesCliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=1000)),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('fecha_nacimiento', models.DateTimeField(blank=True, null=True)),
                ('cliente', models.ForeignKey(db_column='cliente', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Cliente')),
            ],
            options={
                'verbose_name': 'Parientes del Cliente',
                'db_table': 'parientes_cliente',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Periodopos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name': 'Periodo POS',
                'db_table': 'periodopos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Poliza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=1000)),
                ('numero_poliza', models.CharField(blank=True, max_length=1000, null=True)),
                ('fecha_emision', models.DateField(blank=True, null=True)),
                ('fecha', models.DateField(blank=True, default=datetime.datetime(2018, 11, 12, 18, 5, 46, 117574))),
                ('agente', models.ForeignKey(blank=True, db_column='agente', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='polizas', to='app.Agente')),
                ('cliente', models.ForeignKey(blank=True, db_column='cliente', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Cliente')),
            ],
            options={
                'verbose_name': 'Poliza',
                'db_table': 'poliza',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name': 'Producto',
                'db_table': 'producto',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PropuestaCliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacion', models.CharField(max_length=10000)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('detalle', models.CharField(max_length=1000)),
                ('inforce', models.BooleanField(default=False)),
                ('interes', models.CharField(blank=True, max_length=1000, null=True)),
                ('upload_csv', models.BooleanField(default=0)),
                ('upload_csv_julio_enero_2019', models.BooleanField(default=0)),
                ('upload_ene_jul_2019_ecu', models.BooleanField(default=0)),
                ('agente', models.ForeignKey(db_column='agente', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Agente')),
                ('cliente', models.ForeignKey(db_column='cliente', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Cliente')),
            ],
            options={
                'db_table': 'propuesta_cliente',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Ramo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10000)),
            ],
            options={
                'db_table': 'ramo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RamoCompaniaProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('antiguo', models.BooleanField(default=0)),
                ('compania', models.ForeignKey(db_column='compania', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Compania')),
                ('producto', models.ForeignKey(db_column='producto', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Producto')),
                ('ramo', models.ForeignKey(db_column='ramo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Ramo')),
            ],
            options={
                'ordering': ('ramo', 'compania', 'producto'),
                'db_table': 'ramo_compania_producto',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Relacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'relacion',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Semanas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=1000)),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('anio', models.CharField(max_length=1000)),
                ('mes', models.ForeignKey(blank=True, db_column='mes', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Mes')),
            ],
            options={
                'verbose_name': 'Semana',
                'db_table': 'semanas',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Statuspoliza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name': 'Status Poliza',
                'db_table': 'status_poliza',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Subgrupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'subgrupo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TelefonoUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=1000, null=True)),
                ('user', models.ForeignKey(blank=True, db_column='user', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Telefonos del Usuario',
                'db_table': 'telefono_user',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TipoAgente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10000)),
            ],
            options={
                'verbose_name': 'Tipos de Agente',
                'db_table': 'tipo_agente',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TipoCita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name': 'Tipos de Cita',
                'db_table': 'tipo_cita',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TipoSeguimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name': 'Tipos de Seguimiento',
                'db_table': 'tipo_seguimiento',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='propuestacliente',
            name='ramo_compania_producto',
            field=models.ForeignKey(db_column='ramo_compania_producto', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.RamoCompaniaProducto'),
        ),
        migrations.AddField(
            model_name='poliza',
            name='producto',
            field=models.ForeignKey(blank=True, db_column='producto', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.PropuestaCliente'),
        ),
        migrations.AddField(
            model_name='parientescliente',
            name='relacion',
            field=models.ForeignKey(blank=True, db_column='relacion', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Relacion'),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='pais',
            field=models.ForeignKey(blank=True, db_column='pais', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Pais'),
        ),
        migrations.AddField(
            model_name='jerarquia',
            name='nivel',
            field=models.ForeignKey(blank=True, db_column='nivel', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Nivel'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='estado_civil',
            field=models.ForeignKey(blank=True, db_column='estado_civil', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.EstadoCivil'),
        ),
        migrations.AddField(
            model_name='citas',
            name='cliente',
            field=models.ForeignKey(blank=True, db_column='cliente', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Cliente'),
        ),
        migrations.AddField(
            model_name='citas',
            name='modalidad',
            field=models.ForeignKey(blank=True, db_column='modalidad', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Modalidad'),
        ),
        migrations.AddField(
            model_name='citas',
            name='periodopos',
            field=models.ForeignKey(blank=True, db_column='periodopos', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Periodopos'),
        ),
        migrations.AddField(
            model_name='citas',
            name='propuesta_cliente',
            field=models.ForeignKey(blank=True, db_column='propuesta_cliente', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.PropuestaCliente'),
        ),
        migrations.AddField(
            model_name='citas',
            name='ramo_compania_producto',
            field=models.ForeignKey(blank=True, db_column='ramo_compania_producto', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.RamoCompaniaProducto'),
        ),
        migrations.AddField(
            model_name='citas',
            name='semana',
            field=models.ForeignKey(blank=True, db_column='semana', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Semanas'),
        ),
        migrations.AddField(
            model_name='citas',
            name='status_poliza',
            field=models.ForeignKey(blank=True, db_column='status_poliza', default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Statuspoliza'),
        ),
        migrations.AddField(
            model_name='citas',
            name='tipo_cita',
            field=models.ForeignKey(db_column='tipo_cita', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.TipoCita'),
        ),
        migrations.AddField(
            model_name='citas',
            name='tipo_seguimiento',
            field=models.ForeignKey(db_column='tipo_seguimiento', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.TipoSeguimiento'),
        ),
        migrations.AddField(
            model_name='archivo',
            name='compania',
            field=models.ForeignKey(blank=True, db_column='compania', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Compania'),
        ),
        migrations.AddField(
            model_name='archivo',
            name='ramo',
            field=models.ForeignKey(blank=True, db_column='ramo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Ramo'),
        ),
        migrations.AddField(
            model_name='agentecliente',
            name='cliente',
            field=models.ForeignKey(db_column='cliente', default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Cliente'),
        ),
        migrations.AddField(
            model_name='agente',
            name='equipo',
            field=models.ForeignKey(blank=True, db_column='equipo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Equipo'),
        ),
        migrations.AddField(
            model_name='agente',
            name='estructura',
            field=models.ForeignKey(blank=True, db_column='estructura', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Estructura'),
        ),
        migrations.AddField(
            model_name='agente',
            name='grupo_prueba',
            field=models.ForeignKey(blank=True, db_column='grupo_prueba', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Agente'),
        ),
        migrations.AddField(
            model_name='agente',
            name='nivel',
            field=models.ForeignKey(blank=True, db_column='nivel', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Nivel'),
        ),
        migrations.AddField(
            model_name='agente',
            name='pais',
            field=models.ForeignKey(blank=True, db_column='pais', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Pais'),
        ),
        migrations.AddField(
            model_name='agente',
            name='tipo_agente',
            field=models.ForeignKey(blank=True, db_column='tipo_agente', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.TipoAgente'),
        ),
        migrations.AddField(
            model_name='agente',
            name='user',
            field=models.ForeignKey(blank=True, db_column='user', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
