# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-11-13 16:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20181112_2016'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comision', models.CharField(max_length=1000)),
                ('fecha', models.DateTimeField(blank=True, default=datetime.datetime(2018, 11, 13, 16, 37, 29, 387345), null=True)),
                ('agente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Agente')),
            ],
            options={
                'verbose_name': 'Pruebas Comisiones ',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Datocomision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rango_inicio', models.IntegerField(blank=True, null=True, verbose_name='Inicio')),
                ('rango_fin', models.IntegerField(blank=True, null=True, verbose_name='Fin')),
                ('pca_l1', models.FloatField(blank=True, null=True, verbose_name='PCA L1')),
                ('pca_l2', models.FloatField(blank=True, null=True, verbose_name='PCA L1')),
                ('senior_pca', models.FloatField(blank=True, null=True, verbose_name='PCA Sr.')),
                ('relationship_manager', models.FloatField(blank=True, null=True, verbose_name='RM')),
                ('relationship_manager_senior', models.FloatField(blank=True, null=True, verbose_name='RM Sr.')),
                ('relationship_director', models.FloatField(blank=True, null=True, verbose_name='RD')),
                ('bussiness_partner', models.FloatField(blank=True, null=True, verbose_name='BP')),
                ('fecha', models.DateTimeField(blank=True, default=datetime.datetime(2018, 11, 13, 16, 37, 29, 385963), null=True)),
                ('agente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Agente')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='datocomision', to='app.RamoCompaniaProducto')),
            ],
            options={
                'verbose_name': 'Comision',
                'managed': True,
            },
        ),
        migrations.RemoveField(
            model_name='poliza',
            name='producto',
        ),
        migrations.AddField(
            model_name='poliza',
            name='anio_aporte',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='poliza',
            name='comision',
            field=models.FloatField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='poliza',
            name='deducible',
            field=models.IntegerField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='poliza',
            name='fecha_aprobacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='poliza',
            name='fecha_envio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='poliza',
            name='fecha_recibido',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='poliza',
            name='fecha_renovacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='poliza',
            name='forma_pago',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='poliza',
            name='plan',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='poliza',
            name='prima',
            field=models.FloatField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='poliza',
            name='ramo_compania_producto',
            field=models.ForeignKey(blank=True, db_column='ramo_compania_producto', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.RamoCompaniaProducto'),
        ),
        migrations.AddField(
            model_name='poliza',
            name='total',
            field=models.FloatField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 13, 16, 37, 29, 377380)),
        ),
        migrations.AlterField(
            model_name='poliza',
            name='fecha',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 11, 13, 16, 37, 29, 383654)),
        ),
        migrations.AddField(
            model_name='comision',
            name='datocomision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comision', to='app.Datocomision'),
        ),
        migrations.AddField(
            model_name='comision',
            name='tipo_agente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.TipoAgente'),
        ),
    ]
