# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-11-14 17:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20181114_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='agente',
            name='cfp_ramo',
            field=models.BooleanField(default=False, verbose_name='Ramo CFP'),
        ),
        migrations.AddField(
            model_name='agente',
            name='investments',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agente',
            name='ramos_generales',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agente',
            name='salud',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agente',
            name='vida',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='comision',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 11, 14, 17, 3, 19, 106513), null=True),
        ),
        migrations.AlterField(
            model_name='datocomision',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 11, 14, 17, 3, 19, 100618), null=True),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 14, 17, 3, 19, 37681)),
        ),
        migrations.AlterField(
            model_name='poliza',
            name='fecha',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 11, 14, 17, 3, 19, 89620)),
        ),
    ]
