# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-11-14 17:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20181114_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comision',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 11, 14, 17, 6, 16, 374985), null=True),
        ),
        migrations.AlterField(
            model_name='datocomision',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 11, 14, 17, 6, 16, 373605), null=True),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 14, 17, 6, 16, 365289)),
        ),
        migrations.AlterField(
            model_name='poliza',
            name='fecha',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 11, 14, 17, 6, 16, 371287)),
        ),
    ]
