# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-11-15 19:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20181114_1706'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comision',
            options={'managed': True, 'verbose_name': 'Comision/Agente'},
        ),
        migrations.AlterField(
            model_name='cliente',
            name='upload_csv',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='upload_csv_julio_enero_2019',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='upload_ene_jul_2019_ecu',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='comision',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 11, 15, 19, 34, 58, 299652), null=True),
        ),
        migrations.AlterField(
            model_name='datocomision',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 11, 15, 19, 34, 58, 275927), null=True),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 15, 19, 34, 58, 264922)),
        ),
        migrations.AlterField(
            model_name='pais',
            name='nombre',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Pa\xeds'),
        ),
        migrations.AlterField(
            model_name='poliza',
            name='fecha',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 11, 15, 19, 34, 58, 273638)),
        ),
        migrations.AlterField(
            model_name='tipoagente',
            name='nombre',
            field=models.CharField(max_length=10000, verbose_name='Tipo de Agente'),
        ),
    ]
