# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-11-15 19:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20181115_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='periodopos',
            field=models.ForeignKey(blank=True, db_column='periodopos', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Periodopos'),
        ),
        migrations.AlterField(
            model_name='comision',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 11, 15, 19, 55, 20, 241419), null=True),
        ),
        migrations.AlterField(
            model_name='datocomision',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 11, 15, 19, 55, 20, 240018), null=True),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 15, 19, 55, 20, 203868)),
        ),
        migrations.AlterField(
            model_name='poliza',
            name='fecha',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 11, 15, 19, 55, 20, 214232)),
        ),
    ]
